Fix problems in _icuve_ modules
UBESP-DCTV/covid19ita pull request #86
Opened 2020-10-29 14:27 UTC by danielebottigliengo

Apportate le seguenti modifiche:

- Sistemato #84
- Risolto 1/2 di #85
- Risolto problema con l'aggiornamento automatico delle previsioni rappresentate sulla Figure 3 di `mod_icuve_ts`

2020-11-02 04:55 UTC, CorradoLanera requested changes
Ripristina account di default (suggerisco in locale di impostare la relativa opzione nel tuo `.Rprofile` in modo che funzioni con il tuo account senza scriverlo esplicitamente) e controlla il discorso del `last(na.omit(<...>))`. Per il resto, power.

2020-11-02 04:55 UTC, CorradoLanera commented on R/mod_icuve_ts.R
> +  )
Ripristina il default per favore

2020-11-02 04:55 UTC, CorradoLanera commented on R/mod_icuve_ts.R
> +        dplyr::last(stats::na.omit(.data$prop_pos)),
Sicuro che questo faccia quello che vuoi? A ogni dato mancante sostituisci l'ultimo non mancante (sempre lo stesso!)?
es: `c(1, NA, 2, 3, NA)` diventa `c(1, 3, 2, 3, 3)`? Se si, ok.

2020-11-02 05:08 UTC, CorradoLanera commented
@danielebottigliengo quando hai finito aggiungi anche la [descrizione di quello che hai fatto nel file NEWS.md](https://style.tidyverse.org/news.html) (incluso il tuo tag).

2020-11-21 11:26 UTC, danielebottigliengo commented
Ho fatto le modifiche richieste, ma devo aver sbagliato qualcosa perchè non mi fa fare un nuovo pull-request perchè mi dice che ce n'è già uno. @CorradoLanera , hai qualche suggerimento?

2020-11-21 18:29 UTC, CorradoLanera commented
@danielebottigliengo , infatti non devi fare un pull request. devi solo apportare le modifiche a partire dallo stesso ramo da cui hai creato questo pull request (`fix-icuve`)

2020-11-22 15:45 UTC, CorradoLanera approved these changes

2020-11-22 15:46 UTC, merged